### PR TITLE
feat(build): add package toml and script to build collection

### PR DESCRIPTION
**Pull request by domire8**
## Description

This PR adds the option to build the kortex collection locally. @rraetz this means that you can make changes locally, invoke the build script and then package the AICA backend with a toml file that has
```
"kinova-gen3" = "docker-image://ghcr.io/aica-technology/collections_kinova_gen3_collection:latest"
```
in it.

## Review guidelines

Estimated Time of Review: 5 minutes

## Checklist before merging:

- [x] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Comment by rraetz** [comment]
I might be missing something, but I didn't succeed:

```
[+] Building 1.5s (18/24)                                                                                                      docker:default
 => [internal] load build definition from aica-package.toml                                                                              0.0s
 => => transferring dockerfile: 655B                                                                                                     0.0s
 => resolve image config for ghcr.io/aica-technology/app-builder:v1                                                                      0.3s
 => CACHED docker-image://ghcr.io/aica-technology/app-builder:v1@sha256:827090b491133484540a6113f7fb8359ca323049baf07f177812f53e9e816d3  0.0s
 => [aica] load aica-package.toml                                                                                                        0.0s
 => => transferring dockerfile: 39B                                                                                                      0.0s
 => [aica] load base image metadata (registry.licensing.aica.tech/base:v3.1.1)                                                           0.8s
 => [auth] base:pull token for registry.licensing.aica.tech                                                                              0.0s
 => ERROR [aica packages 6/6] adding kinova-gen3 (ghcr.io/aica-technology/collections_kinova_gen3_collection:latest)                     0.1s
 => => resolve ghcr.io/aica-technology/collections_kinova_gen3_collection:latest                                                         0.1s
 => CANCELED [aica packages 3/6] adding @aica/components/pose-detection (registry.licensing.aica.tech/components/pose-detection:v1.0.2)  0.1s
 => => resolve registry.licensing.aica.tech/components/pose-detection:v1.0.2                                                             0.1s
 => CANCELED [aica packages 2/6] adding @aica/components/auto-frame-calibration (registry.licensing.aica.tech/components/auto-frame-cal  0.1s
 => => resolve registry.licensing.aica.tech/components/auto-frame-calibration:v1.0.0                                                     0.1s
 => CANCELED [aica base] using registry.licensing.aica.tech/base:v3.1.1                                                                  0.1s
 => => resolve registry.licensing.aica.tech/base:v3.1.1                                                                                  0.1s
 => CANCELED [aica packages 1/6] adding @aica/collections/ur-collection (registry.licensing.aica.tech/collections/ur-collection:v3.0.4)  0.1s
 => => resolve registry.licensing.aica.tech/collections/ur-collection:v3.0.4                                                             0.1s
 => CANCELED [aica packages 5/6] adding @aica/components/task-optimization (registry.licensing.aica.tech/components/task-optimization:v  0.1s
 => => resolve registry.licensing.aica.tech/components/task-optimization:v3.0.0                                                          0.1s
 => CANCELED [aica packages 4/6] adding @aica/components/signal-processing (registry.licensing.aica.tech/components/signal-processing:v  0.1s
 => => resolve registry.licensing.aica.tech/components/signal-processing:v1.0.1                                                          0.1s
 => [auth] components/auto-frame-calibration:pull token for registry.licensing.aica.tech                                                 0.0s
 => [auth] components/pose-detection:pull token for registry.licensing.aica.tech                                                         0.0s
 => [auth] components/signal-processing:pull token for registry.licensing.aica.tech                                                      0.0s
 => [auth] components/task-optimization:pull token for registry.licensing.aica.tech                                                      0.0s
 => [auth] collections/ur-collection:pull token for registry.licensing.aica.tech                                                         0.0s
------
 > [aica packages 6/6] adding kinova-gen3 (ghcr.io/aica-technology/collections_kinova_gen3_collection:latest):
------
ERROR: failed to solve: failed to load cache key: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aaica-technology%2Fcollections_kinova_gen3_collection%3Apull&service=ghcr.io: 401 Unauthorized
 ```

**Comment by LouisBrunner** [comment]
@rraetz Seems like you need to be logged in to GHCR. See Github documentation: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic

**Comment by domire8** [comment]
@rraetz Sorry I think we misread your problem. The command output that you sent was from the packaging step of the backend [as described here](https://docs.aica.tech/docs/getting-started/installation) right? The steps to make this work are:
1. Check out this branch and run `./build.sh`
2. Verify that `docker images` now contains `ghcr.io/aica-technology/collections_kinova_gen3_collection:latest`
3. Try to package the backend with 
    ```
    "kinova-gen3" = "docker-image://ghcr.io/aica-technology/collections_kinova_gen3_collection:latest"
    ```
    in the toml file

**Comment by domire8** [comment]
I guess this then worked, right @rraetz ?

**Comment by domire8** [comment]
@rraetz the author should be the one to merge the pull requests. Ideally, we also chose the `Squash and merge` option when merging PRs to keep main branch clean.

**Pull request merged**
